spring.application.name=backend

spring.datasource.url=jdbc:mysql://localhost:3306/financas
spring.datasource.username=financas
spring.datasource.password=financas

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
